package com.epam.task.controller;

public enum Parameters {
    ADDITIONAL_PHONE_NUMBER, APARTMENT_NUMBER, CITY, COMMENT, EMAIL, GROUP, HOME_PHONE_NUMBER,
    HOUSE_NUMBER, INDEX, NAME,
    NICKNAME, PATRONYMIC, PHONE_NUMBER, STREET, SURNAME;
}
